### ISSUE TITLE
BuyEnergyFromOffer shouldn't it delete closed offer?

### ISSUE THREAD

**Issue by mknezevic** [BC4GRID/energy-trading#10]
https://github.com/BC4GRID/energy-trading/blob/9ebbbe67e9601096e6e772236139d33b011f92c9/Trading.sol#L99C46-L99C46

Shouldn't a completely realized offer be deleted from the mapping `offers`?

**Comment by frostymuaddib** [comment]
There is no need to delete an offer. Mappings in Solidity are designed in a way that every possible key is mapped to a value, so the only way to 'delete' the value would be to initialize all the fields to default (zero) value, which would only add to the cost of the function.
