### ISSUE TITLE
ModifyOffer should require change in at least one field

### ISSUE THREAD

**Issue by mknezevic** [BC4GRID/energy-trading#12]
Sada je moguce poslati `ModifyOffer` gde su sve vrednosti (`energyAmount`, `pricePerEnergyUnit`, `validUntil`) jednake sa onim iz ponude koja se menja. Ako se kroz adekvatni require sprecava bespotrebno trosenje ethera (izmena kojom se zapravo nista ne menja), trebalo bi dodati taj require.

**Comment by frostymuaddib** [comment]
Added the needed `require`
