### ISSUE TITLE
List of expired offers

### ISSUE THREAD

**Issue by mknezevic** [BC4GRID/energy-trading#13]
Posto ListOffers i GetAllOfferDetails vracaju samo aktivne ponude (`validUntil > block.timestamp`) korisnik ne moze da dobije spisak svojih isteklih ponuda kako bi povratio tokene sa njih. Neophodno je ovo resiti, npr. dodavanjem nove funkcije `GetExpiredOffersForUser(address)` ili slicno.

**Comment by frostymuaddib** [comment]
Решено овим: https://github.com/BC4GRID/energy-trading/issues/15#issue-1972097925
