### ISSUE TITLE
Additional info in OfferClosed event

### ISSUE THREAD

**Issue by mknezevic** [BC4GRID/energy-trading#16]
Mislim da bi bilo korisno da OfferClosed event sadrzi i dodatne podatke o ponudi i kupcu. Na taj nacin se omogucava podrska za dodatne funkcionalnosti, npr. korisnik moze pregledati sve svoje ranije (zatvorene) ponude u kojima je ucestvovao kao kupac/prodavac, mogu se prikazati grafici realizovanih cena (istorijsko kretanje cena) i sl.

Ako dodamo i polje buyer, moci cemo da razlikujemo istekle ponude od realizovanih.

**Comment by frostymuaddib** [comment]
Ако додамо купца, морамо онда некако да га убацимо и у OfferModified, јер неко не мора да купи све токене из понуде. Могли бисмо да додамо buyer у OfferModified, па ако је ова вредност 0x0, онда није ништа купљено а промена је мењана, иначе је дошло до промене због куповине?

**Comment by mknezevic** [comment]
Slažem se.

**Comment by frostymuaddib** [comment]
Reseno
