### ISSUE TITLE
function ListOffers should return offer details

### ISSUE THREAD

**Issue by mknezevic** [BC4GRID/energy-trading#4]
ListOffers returns only offer ids. It should return offer details for each existing offer.

**Comment by frostymuaddib** [comment]
Implemented GetAllOfferDetails  function that returns offer details for each existing offer. Old ListOffers kept, but is deprecated and may be removed.

**Comment by mknezevic** [comment]
GetAllOfferDetails has to return offerID as well.

**Comment by frostymuaddib** [comment]
GetAllOfferDetails and ListExpiredOffersWithAmount now return offerID as well
