### ISSUE TITLE
GetOfferDetails to return offer id

### ISSUE THREAD

**Issue by mknezevic** [BC4GRID/energy-trading#6]
Mislim da ne bi bilo lose da GetOfferDetails vraca i ID

https://github.com/BC4GRID/energy-trading/blob/9ebbbe67e9601096e6e772236139d33b011f92c9/Trading.sol#L187C5-L187C5

**Comment by frostymuaddib** [comment]
Nisam stavio da vraca jer je ID argument funkcije, a funkcija kosta vise gas-a sto vise stvari vraca pa sam tu hteo da ustedim. Ako mislis da treba zbog uniformnosti, ubacicu.

**Comment by mknezevic** [comment]
Kada kazes kosta vise pp da se to odnosi na postavljnje pametnog ugovora, jer ovo je view/pure?

**Comment by frostymuaddib** [comment]
Da, mislio sam na postavljanje. Mada sad kad razmislim, to nama nije toliko bitno, pa cu ubaciti.

**Comment by frostymuaddib** [comment]
Dodato.
